# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\tmp\SCD3\inform.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_inForm(object):
    def setupUi(self, inForm):
        inForm.setObjectName("inForm")
        inForm.resize(400, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(160)
        sizePolicy.setVerticalStretch(120)
        sizePolicy.setHeightForWidth(inForm.sizePolicy().hasHeightForWidth())
        inForm.setSizePolicy(sizePolicy)
        inForm.setMinimumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setPointSize(12)
        inForm.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(inForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cButton = QtWidgets.QPushButton(inForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cButton.sizePolicy().hasHeightForWidth())
        self.cButton.setSizePolicy(sizePolicy)
        self.cButton.setObjectName("cButton")
        self.horizontalLayout.addWidget(self.cButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(inForm)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.plainTextEdit)

        self.retranslateUi(inForm)
        QtCore.QMetaObject.connectSlotsByName(inForm)

    def retranslateUi(self, inForm):
        _translate = QtCore.QCoreApplication.translate
        inForm.setWindowTitle(_translate("inForm", "import"))
        self.cButton.setText(_translate("inForm", "解析c代码"))
