# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\qt_msvc_shared\SCD3\luaform.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_luaForm(object):
    def setupUi(self, luaForm):
        luaForm.setObjectName("luaForm")
        luaForm.resize(800, 600)
        luaForm.setMinimumSize(QtCore.QSize(400, 300))
        font = QtGui.QFont()
        font.setPointSize(12)
        luaForm.setFont(font)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(luaForm)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(luaForm)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setContentsMargins(-1, 16, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit1_1 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit1_1.setObjectName("lineEdit1_1")
        self.horizontalLayout_2.addWidget(self.lineEdit1_1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit1_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit1_2.setObjectName("lineEdit1_2")
        self.horizontalLayout_2.addWidget(self.lineEdit1_2)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.loadButton1 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadButton1.sizePolicy().hasHeightForWidth())
        self.loadButton1.setSizePolicy(sizePolicy)
        self.loadButton1.setObjectName("loadButton1")
        self.horizontalLayout_2.addWidget(self.loadButton1)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.setStretch(3, 3)
        self.horizontalLayout_2.setStretch(5, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.lineEdit2_1 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit2_1.setObjectName("lineEdit2_1")
        self.horizontalLayout_3.addWidget(self.lineEdit2_1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.lineEdit2_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit2_2.setObjectName("lineEdit2_2")
        self.horizontalLayout_3.addWidget(self.lineEdit2_2)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.loadButton2 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadButton2.sizePolicy().hasHeightForWidth())
        self.loadButton2.setSizePolicy(sizePolicy)
        self.loadButton2.setObjectName("loadButton2")
        self.horizontalLayout_3.addWidget(self.loadButton2)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout_3.setStretch(3, 3)
        self.horizontalLayout_3.setStretch(5, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(luaForm)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_4.setContentsMargins(-1, 16, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.lineEdit3_1 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit3_1.setObjectName("lineEdit3_1")
        self.horizontalLayout_4.addWidget(self.lineEdit3_1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.lineEdit3_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit3_2.setObjectName("lineEdit3_2")
        self.horizontalLayout_4.addWidget(self.lineEdit3_2)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.loadButton3 = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadButton3.sizePolicy().hasHeightForWidth())
        self.loadButton3.setSizePolicy(sizePolicy)
        self.loadButton3.setObjectName("loadButton3")
        self.horizontalLayout_4.addWidget(self.loadButton3)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(luaForm)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_3.addWidget(self.plainTextEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.loadButton = QtWidgets.QPushButton(luaForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadButton.sizePolicy().hasHeightForWidth())
        self.loadButton.setSizePolicy(sizePolicy)
        self.loadButton.setObjectName("loadButton")
        self.horizontalLayout.addWidget(self.loadButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.clearButton = QtWidgets.QPushButton(luaForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearButton.sizePolicy().hasHeightForWidth())
        self.clearButton.setSizePolicy(sizePolicy)
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout.addWidget(self.clearButton)
        self.exeButton = QtWidgets.QPushButton(luaForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exeButton.sizePolicy().hasHeightForWidth())
        self.exeButton.setSizePolicy(sizePolicy)
        self.exeButton.setObjectName("exeButton")
        self.horizontalLayout.addWidget(self.exeButton)
        self.exe_clr_Button = QtWidgets.QPushButton(luaForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exe_clr_Button.sizePolicy().hasHeightForWidth())
        self.exe_clr_Button.setSizePolicy(sizePolicy)
        self.exe_clr_Button.setObjectName("exe_clr_Button")
        self.horizontalLayout.addWidget(self.exe_clr_Button)
        self.verticalLayout_3.addLayout(self.horizontalLayout)

        self.retranslateUi(luaForm)
        QtCore.QMetaObject.connectSlotsByName(luaForm)

    def retranslateUi(self, luaForm):
        _translate = QtCore.QCoreApplication.translate
        luaForm.setWindowTitle(_translate("luaForm", "lua script"))
        self.groupBox.setTitle(_translate("luaForm", "DUMP"))
        self.label.setText(_translate("luaForm", "scd_dump("))
        self.lineEdit1_1.setPlaceholderText(_translate("luaForm", "listNum"))
        self.label_2.setText(_translate("luaForm", ","))
        self.lineEdit1_2.setPlaceholderText(_translate("luaForm", "dumpNums"))
        self.label_3.setText(_translate("luaForm", ");"))
        self.loadButton1.setText(_translate("luaForm", "插入"))
        self.label_4.setText(_translate("luaForm", "scd_dumpOut("))
        self.lineEdit2_1.setPlaceholderText(_translate("luaForm", "colCnt"))
        self.label_6.setText(_translate("luaForm", ",\""))
        self.lineEdit2_2.setPlaceholderText(_translate("luaForm", "win(default)/cb/cmd/csv"))
        self.label_5.setText(_translate("luaForm", "\");"))
        self.loadButton2.setText(_translate("luaForm", "插入"))
        self.groupBox_2.setTitle(_translate("luaForm", "CALL"))
        self.label_7.setText(_translate("luaForm", "scd_call("))
        self.lineEdit3_1.setPlaceholderText(_translate("luaForm", "listNum"))
        self.label_8.setText(_translate("luaForm", ","))
        self.lineEdit3_2.setPlaceholderText(_translate("luaForm", "int32_t para"))
        self.label_9.setText(_translate("luaForm", ");"))
        self.loadButton3.setText(_translate("luaForm", "插入"))
        self.loadButton.setText(_translate("luaForm", "载入"))
        self.clearButton.setText(_translate("luaForm", "清除"))
        self.exeButton.setText(_translate("luaForm", "执行"))
        self.exe_clr_Button.setText(_translate("luaForm", "执行并清除"))
        self.exe_clr_Button.setShortcut(_translate("luaForm", "Ctrl+Return"))

